### ISSUE TITLE
ERROR:  Not enough natural land points in selected area

### ISSUE THREAD

**Issue by FishyEric** [matthiasdemuzere/w2w#116]
Dear all experts,

When I tried to ran w2w on Chicago area, I met this error:

![image](https://user-images.githubusercontent.com/131193874/232858683-dcd14a57-ba13-4b2e-9303-08f4043ae0a9.png)

Does this mean that the selected domain must contain certain amount of non-urban land points?
If so, how many land points must be included in the domain?

Thanks,
Eric

**Comment by jkittner** [comment]
Dear Eric,
- please use the issue template it's there for a reason!
- please don't send images of errors, since they are not searchable, and search engines can't index them

The error literally says what's wrong: _Not enough natural land points in selected area_...
...and how to fix it: _Increase NPIX_AREA_
