### ISSUE TITLE
Loop in wrf_remove_urban doesn't finish

### ISSUE THREAD

**Issue by jcperezull** [matthiasdemuzere/w2w#3]
Running w2w over a Barcelona LCZ file, the program hangs in the wrf_remove_urban function. Trying to debug the program, it seems that it remains forever in the for loop.
Attached are the files we are using to run w2w
[geo_em.d04.nc.gz](https://github.com/matthiasdemuzere/w2w/files/6950947/geo_em.d04.nc.gz)
[Barcelona.tif.gz](https://github.com/matthiasdemuzere/w2w/files/6950948/Barcelona.tif.gz)

**Comment by matthiasdemuzere** [comment]
Hi @jcperezull,

I believe you are using [this LCZ map](https://lcz-generator.rub.de/factsheets/ce2824ec10a2ab08183c96849cd094ae660042e2/ce2824ec10a2ab08183c96849cd094ae660042e2_factsheet.html) created with our LCZ Generator?

The resulting .tif has 3 bands, and you should use the "lczFilter" one. This can be done by using the argument `-lcz_band 1` when launching the script (see also Help / README). So in your case:

`python w2w.py -lcz_band 1 INPUT_DIR/ Barcelona.tif geo_em.d04.nc`

This works for me.

You will get a warning at the end, referring to the fact that files .d01-d03 could not be processed, as they are not available. So please make sure that these are also available in your INPUT_DIR/, so that the script can process them as well.

**Comment by jcperezull** [comment]
Hi Matthias
Thank you very much for your fast answer. I Will try ASAP. I ley you know.
Regards,

**Comment by matthiasdemuzere** [comment]
We have packaged the first version of w2w.py now. 
In case your issue still persists, please try to install via: `pip install w2w`

See here: [https://pypi.org/project/w2w/](https://pypi.org/project/w2w/)
