### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by JulioCM** [matthiasdemuzere/w2w#33]
Hi,

When using w2w (version 0.1.1) with geo_em files generate with WPS 4.3. and with a LCZ map generated with the LCZ generator that I have downloaded from https://lcz-generator.rub.de/submissions, I get the following error

"IndexError: index 20 is out of bounds for axis 0 with size 20"

I've attached the complete log file

Many thanks

Julio

[log.txt](https://github.com/matthiasdemuzere/w2w/files/7953934/log.txt)

**Comment by matthiasdemuzere** [comment]
Hi,

Could you please also: 

1. provide the geom_files netcdf files
2. provide the link to your actual LCZ submissions, and not the one to the full submissions table?

This data is required for me to debug this problem.

Also, since you are using a map from the LCZ Generator, make sure to the the argument `-l 1`.
 
Cheers,
Matthias

**Comment by JulioCM** [comment]
Many thanks Matthias,

I've changed modis_15s to modis_15s_lake  in WPS and now I have generated succesfully the geo_em0X files with the LCZ data. Is it mandatory tu use Modis with lakes in w2w?

Kind Regards

Julio

**Comment by matthiasdemuzere** [comment]
Hi Julio,

That sounds good already.

Let me tag @dargueso here, as he developed the part where urban pixels are converted to natural land.
Daniel: it seems that `wrf_remove_urban()` is sensitive to whether or not lakes are present, depending on the input dataset that is used in WPS (modis_15s versus modis_15s_lake).

I think that ideally this should not be the case? Any suggestion you can make in this respect?

**Comment by dargueso** [comment]
Sure! On my to-do list for this week

**Comment by dargueso** [comment]
When the code searchers for the nearest n points to remove urban land use fraction, it discards other urban points, water points (ocean) and lakes (category 21). If no lakes are included, the land use fraction array has only 20 levels, and this make it crash. I need to think about a solution to consider cases both with and without lakes. One possible solution is to expand the land_cat array (already done at some other part of the code for the parent domains) or add some IFs to include both options. 
I'll work on it.

**Comment by dargueso** [comment]
This should be fixed now.

**Comment by matthiasdemuzere** [comment]
Great, thanks @dargueso!

@JulioCM: have a look at this implementation #34. 
Could you test whether this new branch works? You can install it via `pip install  git+https://github.com,/matthiasdemuzere/w2w.git@Daniel'-branch-name -modis_lakes`

**Comment by matthiasdemuzere** [comment]
@sobrinhotavio: since you had the same issue (reported via email), you might want to test this as well.
Please provide feedback here.

**Comment by sunqiccgk** [comment]
Hello,I met this problem too. I use the LCZ data from this website ( https://wudapt.cs.purdue.edu/wudaptTools/default/city_for_wrf : I don't know why the tiff data converted to WRF already still have so much problems as below) and 
1. the urban type index in the tiff range in  (1-10 then 101-107) and I use python change it to 1-17 which made it same with sample.
2. change the  Geographic coordinate system to WGS 1984 which help the tiff can be in same system,
3. then use w2w, it still said"IndexError: index 20 is out of bounds for axis 0 with size 20" too, plus, I use  WRF v4.3.4 and use defult terrain.
plus: Do u have some better LCZ tiff ? 
Thanks A lot!
Qi

**Comment by dargueso** [comment]
Hi @sunqiccgk, I can't personally help you with the tiff (maybe @matthiasdemuzere can), but I can with point #3. Could you please send me the data you used that threw the error? Thanks!

**Comment by dargueso** [comment]
Hi all, 
I have run the latest version of the code with MODIS+Lakes (21 categories) and it didn't crash. It is actually the default land use AFAIK. 
Please make sure you have updated to the latest version where this has been fixed. If you still have issues, please send me your data so I can try track down the problem.
Cheers,
Dani

**Comment by sunqiccgk** [comment]
hi @dargueso  
  I try again this but still have same error.
              The following file is my domain nc file and tiff file, could you please help me find where is the problem? And I also screenshot the WPS version and the land dataset used in geogrid. If you need any further information, please contact me!
              Thanks A lot!
[shanghai_domain.zip](https://github.com/matthiasdemuzere/w2w/files/8059603/shanghai_domain.zip)

           
![772860094506959349](https://user-images.githubusercontent.com/99535285/153838980-13abc941-77a6-4a18-97f4-6df930dfe834.jpg)
![887389495652560331](https://user-images.githubusercontent.com/99535285/153839001-13a0c424-afd7-459a-a65c-11f79efdd973.jpg)
![ef15689755148373769aaf602e08abc](https://user-images.githubusercontent.com/99535285/153839006-bf5eda82-b40e-4351-8a23-2bbf7dac70f7.png)

Cheers,
Qi

**Comment by sunqiccgk** [comment]
Hi @matthiasdemuzere 
    I use the LCZ data from this website ( https://wudapt.cs.purdue.edu/wudaptTools/default/city_for_wrf ) for exmaple :shanghai , but it cannot be used directly by WRF , there are some problems, could you please help me check why this tiff have problems?
[shanghai_domain.zip](https://github.com/matthiasdemuzere/w2w/files/8059699/shanghai_domain.zip)

I put the origin tiff file in the attachment file and the nc file.

Thanks A lot!
Qi

**Comment by dargueso** [comment]
Hi @sunqiccgk, 
Sorry the bug was still there in a different form. I have fixed it now and run it successfully with your sample data.
Please try yourself to make sure everything is fine.

You can install it via `pip install git+https://github.com/matthiasdemuzere/w2w.git@modis_lakes`

Please let me know how it goes.

**Comment by dargueso** [comment]
Hi @sunqiccgk, 

I have fixed the code and successfully run it on your sample data.
Please try it yourself and let me know how it goes.

You can install this version via:
`pip install git+https://github.com/matthiasdemuzere/w2w.git@modis_lakes`

Cheers

**Comment by sunqiccgk** [comment]
Hi @dargueso 
There is a new problem.
![7e180dfcef587d65112d3168a7e722e](https://user-images.githubusercontent.com/99535285/153847975-bbd63450-a098-4db5-a3ca-6b3ba841b7d1.png)

**Comment by dargueso** [comment]
Hi @sunqiccgk, 
I submitted an intermediate version and sent you the comment, but not the final one. The last version works fine, that error was also fixed.

**Comment by sunqiccgk** [comment]
Hi @dargueso  thank A lot!

**Comment by sunqiccgk** [comment]
Hi @dargueso  I have a question about the nc file , in the draft version citable documentation it said in the workflow step 5: NUM_LAND_CAT is set to 41 not only the high resolution domain file, but also lower resolution parent domain files.
But in my file, the domian 1 nc file have not be changed. So I want to make sure that all the domain files have been changed in this parameter? Because I set this parameter in the namelist.input,  it always mismatch between d01 and d02.

![faf68a35c5a6fa19248fb737f05655f](https://user-images.githubusercontent.com/99535285/153888002-a1d9e0c1-3f68-4fb3-858c-caec9eb34367.png)

![116676127762397274](https://user-images.githubusercontent.com/99535285/153888047-29806e64-f14d-42fe-a64f-63e5c546a438.jpg)

Thanks A lot!

Cheers,
Qi

**Comment by matthiasdemuzere** [comment]
> [sunqiccgk](/sunqiccgk)

If the parent lower resolution domain files are in the same folder of your highest resolution domain file, than `NUM_LAND_CAT` should have changed its file. Can you please confirm that all domain files are in the same folder when applying the w2w routine?

**Comment by dargueso** [comment]
@matthiasdemuzere the parent domain is unchanged, as far as I can tell. I'm investigating the expect and the actual behaviour for this.

**Comment by matthiasdemuzere** [comment]
> Hi @matthiasdemuzere I use the LCZ data from this website ( https://wudapt.cs.purdue.edu/wudaptTools/default/city_for_wrf ) for exmaple :shanghai , but it cannot be used directly by WRF , there are some problems, could you please help me check why this tiff have problems? [shanghai_domain.zip](https://github.com/matthiasdemuzere/w2w/files/8059699/shanghai_domain.zip)
> 
> I put the origin tiff file in the attachment file and the nc file.
> 
> Thanks A lot! Qi

Perhaps first: the files on the WUDAPT portal are no longer supported, that is why the W2W tool is not designed to work with these files.

As far as I can see, there are two main reasons why the tool does not work:
1. The natural classes are labelled 101 to 107, instead of the expected 11 to 17. This might make the tool fail, even to it mainly targets the built LCZ classes 1 to 10. 
2. The old LCZ maps in the portal are provided in WGS84 - UTM Zone x N/S, which is different from EPSG 4326 W2W expects.

I would have to look into these two items to check whether the tool can be made more flexible to take into account these two elements. I'll open 2 separate new issues for those ...

For the time being, you could check whether the LCZ maps you are interested in are available from the [LCZ Generator submission's table](https://lcz-generator.rub.de/submissions)?

**Comment by dargueso** [comment]
The should be fixed now. The original number of categories is no longer hard-coded. It now reads the original file and gets the number of categories.

A test for 20-cat was also included (remove urban areas).

**Comment by theendlessriver13** [comment]
> You can install this version via: `pip install git+https://github.com/matthiasdemuzere/w2w.git@modis_lakes`

I was merged into the main branch now, so please use this instead now `pip install git+https://github.com/matthiasdemuzere/w2w`.

**Comment by sunqiccgk** [comment]
HI @theendlessriver13  there maybe sth wrong with this :
![2f34e07161ebffc3807548c6be759a2](https://user-images.githubusercontent.com/99535285/154067471-0222678d-1d41-4bbd-93da-ac345e9869c9.png)

**Comment by theendlessriver13** [comment]
> please use this instead now `pip install git+https://github.com/matthiasdemuzere/w2w`

As I said above, the branch was merged and therefore deleted. Please reinstall from the main branch now with the command I provided. We have also added a test for this case so it should work now.

**Comment by sunqiccgk** [comment]
Hi @theendlessriver13  Thanks A lot! It works now!

**Comment by theendlessriver13** [comment]
fixed in #34
