### ISSUE TITLE
Metgrid can't process modified geo_em.nc

### ISSUE THREAD

**Issue by yy522** [matthiasdemuzere/w2w#43]
Hello,

I'm using WRF and WPS V4.3. The new geo_em.d0X.nc files can't be processed by metgrid.exe with the following error:

ERROR: In read_next_field(), problems with ext_pkg_get_var_info()

It looks like the modified fields in geo_em.d0X_LCZ_params.nc are somehow not in the expected form to be read by the program.

Any suggestons?

Thank you

**Comment by matthiasdemuzere** [comment]
Hi @yy522,

Likely it is related to the netcdf/hdf libraries used to compile WRF and WPS. Have a look at this thread #23, and references in there.

If not that, then it would be nice to get some more info on your system, module versions etc to understand where this problem comes from. Also, please provide the geo_em.d0X_LCZ_params.nc file, so that we can have a look.

**Comment by andreazonato** [comment]
Hi @yy522,

as @matthiasdemuzere suggests, I think it is related to the compilation of netcdf/HDF5. 

Better to provide the geo_em* files, so we can have a look at them.

**Comment by yy522** [comment]
Hello,

Thanks please get the NC files via this link: https://yale.box.com/s/nsbhi2552i8198istecz214ng4whk2p3

Basically I'm using WRF on a remote machine, which is cheyenne super computer provided by NCAR. I use intel/17.0.1 and netcdf/4.4.1.1, ncl/6.6.2 for the compilation. I'm not sure if the versions are too old for WRF/WPS 4.3. But please let me know what you find by taking a look of the files I shared.

Thank you so much!
Yichen

**Comment by yy522** [comment]
Hi,

How to check if my programs are compiled with netcdf/HDF 5? I only remember that when I configured WRF, I saw a message "This build of WRF will use NETCDF4 with HDF5 compression" when it's completed. Not sure if anything went wrong for the compilation and WPS built-up afterwards.

**Comment by andreazonato** [comment]
@yy522 , I have access to the Cheyenne machine. Could you please say me which is your folder and give me access to it so I can check?

Thanks

Andrea

**Comment by yy522** [comment]
> @yy522 , I have access to the Cheyenne machine. Could you please say me which is your folder and give me access to it so I can check?
> 
> Thanks
> 
> Andrea

Hello!

The folder is "/glade/scratch/yichenyang/URBAN1" in which I have WRF and WPS folders. I think people who also have access to glade can visit the data folder of anyone else. Let me know if you get any difficulties. Many thanks!

Yichen

**Comment by yy522** [comment]
Hi Andrea,

I'm grateful. Sure I can give you access but I'm not sure what is the best way to do so. Can you give me your personal email and I send you my ucar account & password. Let me know when you want to login so I approve on my side via DUO. Does that sound good or do you recommend a better way?

Thank you very much

**Comment by yy522** [comment]
Thank you for trying to solve with hands-on practice!  The python package looks promising so I'm trying to stick to this method for my following simulations.

**Comment by matthiasdemuzere** [comment]
@yy522 

To check if its really a netcdf4/hdf5 incompatibility with WRF, perhaps you can test thnetcdf3_64bit branch.

* Install: 
`pip install  --upgrade --force-reinstall git+https://github.com/matthiasdemuzere/w2w.git@netcdf3_64bit`

* Execute (provide your own parameters!):
`w2w input/folder lcz.tif geo_em.d0X.nc`

In this branch I explicitly set the netcdf format to NETCDF3_64bit when writing the netcdf files, see info [here](https://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_netcdf.html). There is no netcdf4 and hdf5 involved, so this could also provide a way to test if this is causing your problems ...

**Comment by yy522** [comment]
Hello,

I want to follow up on this issue. I tried the netcdf3_64bit branch and it works well this time. Upon using 'w2w input/folder lcz.tif geo_em.d0X.nc', some warnings popped up but finally it was completed without a failure. The metgrid can process the new geo_em's and the wrf run went as expected. (I got weird wrfoutput but think it's not related to this tool).

So all in all, I want to thank you for spending your time on this issue. I'm still not sure how to make sure my wrf is compiled with Netcdf4&hdf5, but the Netcdf3 version works on my side. Is there a reason that we need to eventually use the Netcdf4 version and avoid using the Netcdf3 version?

**Comment by matthiasdemuzere** [comment]
Hi @yy522,

Thanks for trying out the branch that uses netcdf3. Good to know that this works.
A history of netcdf formats is e.g. available [here](https://www.slideshare.net/HDFEOS/netcdf4-tutorial-ws14). 
Netcdf4 has the standard since 2008, and thus I'd like to keep this as the default output type.

But, @theendlessriver13, perhaps we could built-in an optional argument that allows users to set netcdf3 in case they struggle to read the netcdf4 type output into WRF? This error will appear when WRF has been compiled with older netcdf versions, so there is not much we can do about this. Yet also a user might not be able to deal with this, in case WRF is used on computing systems on which a user has no sudo privileges, and can thus not easily re-compile the model ...

**Comment by theendlessriver13** [comment]
I am not sure if it is our job to address this. The only future proof solution would be to recompile it. And moving away from something that has a newer version since 2008 does not seem too quick

**Comment by matthiasdemuzere** [comment]
Yeah, I gave this some more thought and I agree. So I'll close this issue here.
