### ISSUE TITLE
change -l argument approach, extract band choice from .tif data itself?

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/w2w#45]
Based on the Issues so far, I believe it is not always clear for the user when to use the 
`-l , --lcz-band  Band to use from LCZ file (DEFAULT: 0). For maps produced with LCZ Generator, use 1` 
argument.

Now, files created by the LCZ Generator have `long_names` as attributes, where the second one is 'lczFilter':
`long_name:     ('lcz', 'lczFilter', 'classProbability')`

An internal check could be done to see if this long name is present, so that the second band is automatically chosen.
But the -l argument option could be kept, in case someone has a different format of LCZ map ...

Any thoughts on this?

**Comment by theendlessriver13** [comment]
sounds good to me. So not specifying any argument would be your function checking if the tif is from the Generator and then choosing band 1 (we should have a message saying that this was chosen) otherwise still use band 0 as default. Specifying the `--lcz-band` argument overrides everything? correct?
