### ISSUE TITLE
Shift in LCZ substituted values? 

### ISSUE THREAD

**Issue by mgbadas** [matthiasdemuzere/w2w#56]
@matthiasdemuzere thanks a lot for sharing w2w! 
I am trying to use it in a domain in Italy but I obtain a shift in urban settlements. 
You can see in the left plot original LU_Index (from geo_em.d03.nc) and in the left one LU_INDEX from geo_em.d03_LCZ_extent.nc
New classes are added but they are shifted with respect to original urban data, I get urban settlements in the sea!
![test_Rome_LCZ](https://user-images.githubusercontent.com/43202792/167115790-72454986-4528-494a-9515-c80d50355c4c.png)
This is my geo file https://drive.google.com/file/d/1BAvlREj9bJo_sgVQ4EMqs96QAvlhZPug/view?usp=sharing
I cannot understand what the problem might be. The LCZ file used for w2w is  EU_LCZ_map_epsg4326.tif (and was downloaded from https://figshare.com/articles/dataset/European_LCZ_map/).
I also tried with your Shanghai files in the testing folder and it seems that not all the  LU_Index urban cells are substituted.
![test_Shanghai](https://user-images.githubusercontent.com/43202792/167117259-2c27aa2e-6eae-446d-897a-e121233f86dd.png)

Is there something I am missing?

Thanks a lot for your help!

**Comment by matthiasdemuzere** [comment]
@dargueso: for the Italy case, I have the impression that there is truly a shift in the while grid? Looking at the shape of the pixels that are shifted, it is as if the the LCZ urban information is shifted to the South (South of Napoli), yet also to the East (North of Pescara) ...

I am not sure what is going on here .... but I don't think using the landmask is the right approach here, as this would still lead to a bad urban representation (assuming that the LCZ layer is shifted as a whole).

I should probably check the source LCZ EU data first, to make sure this re-projected version is ok?

**Comment by dargueso** [comment]
@matthiasdemuzere, yes, you're right. I was looking only at the south, but looking to the east of the domain, it is quite clear that it is shifted...

**Comment by pippo2013** [comment]
Dear @dargueso, thanks a lot for your reply. I understand the possible mismach between original LCS map due to the upscaling to WPS grid. However, at least in my data, there is a shift between the two geo_em files (the original WPS file and the one obtained with w2w, namely geo_em.d03_LCZ_extent.nc and geo_em.d03_LCZ_parameter.nc). Rome is clearly shifted towards South-East and the red spots in the sea draw the Western Italian coastal line.

**Comment by pippo2013** [comment]
Thank you @dargueso and @matthiasdemuzere , I wrote my last message before refreshing the page! Thank you for checking.

**Comment by matthiasdemuzere** [comment]
@pippo2013

The _epsg4326 version was created afterwards, to easen some of the processing.

But this new version of w2w is able to detect different projection system, and reproject if needed.
Could you therefore re-try your analysis using the [original EU LCZ tif](https://figshare.com/ndownloader/files/25666730)?

I just want to see whether perhaps the reprojected EPSG:4326 version is wrong ...

**Comment by pippo2013** [comment]
Thanks @matthiasdemuzere for your prompt help! I plotted your w2w data but the result is just the same
![Italy_test](https://user-images.githubusercontent.com/43202792/167157275-68bb5c5c-5c7c-4171-aa8c-9dcd9f277f53.png)

I cannot do it immediately, but I will try to use the original EU LCZ tif asap and let you know.

**Comment by matthiasdemuzere** [comment]
Hi @pippo2013,

I am actually a bit puzzled by the behaviour ... not sure where to look for a solution.

As a start, could you report here your w2w version:
`> w2w --version`

and the versions of the packages installed in your environment? 
`> pip list`

**Comment by matthiasdemuzere** [comment]
@pippo2013:

I double-checked the projection definition of the European LCZ map, and I believe something was wrong in that file.
I  have fixed this, and uploaded a new version of the file to Zenodo ([here](https://figshare.com/articles/dataset/European_LCZ_map/13322450/4)).

May I ask you to:
1. Download the EU map again, this time only available in the European LAEA projection
2. Clip your area of interest, that is larger in all directions than your geo_em file
3. Run w2w again -> the routine should also reproject the LCZ data
4. Analyse the results
5. Report back here.

I hope this will solve your issue.

**Comment by matthiasdemuzere** [comment]
A small update.

So, I double checked the new European LCZ map in QGIS. I do think the projection definition is now ok.

I also checked the internal w2w reprojection, done [here](https://github.com/matthiasdemuzere/w2w/blob/18e484048211487e140e3a2f97acbcec2f09de5a/w2w/w2w.py#L356). This also looks fine to me.

As such, I think the problem is situated in the geo_em file itself?

In order to resample between the LCZ tif and the geo_em grid definition, w2w writes out a temporary .tif file derived from the geo_em netcdf file. This is done [here](https://github.com/matthiasdemuzere/w2w/blob/18e484048211487e140e3a2f97acbcec2f09de5a/w2w/w2w.py#L512), after the replacement of the urban LC with surrounding natural LC (for which the output is ok).

So I get the feeling the problem lies in the geo_em file itself?

[Here](https://github.com/matthiasdemuzere/w2w/files/8662168/geo_em.d03_gridinfo.zip) you can find the temporary _gridinfo.tif that is extracted from the geo_em netcdf file. If you open this one in QGIS, you'll see that there is a shift compared to e.g. the openstreetmap layer ...

So perhaps you could first look into your geo_em netcdf file?

**Comment by matthiasdemuzere** [comment]
Thanks for these additional tests.

Though it is not solved yet, I do think it is getting more clear where the problem starts!
That's a start. I'll look into this later on ...

**Comment by pippo2013** [comment]
Hi! I read this very interesting post on WRF projection https://fabienmaussion.info/2018/01/06/wrf-projection/
it explains how to properly convert WRF Lambert conformal projection (using all the geo_em parameters and considering  the earth as a sphere) and shows how shift may arise if this is not taken into account. I hope it helps.

**Comment by matthiasdemuzere** [comment]
After testing a lot of things, I now understand where I made a mistake.
I am treating the WRF coordinates as if they are on a regular grid, by taking the first row/column for lat and lon values, see [here](https://github.com/matthiasdemuzere/w2w/blob/18e484048211487e140e3a2f97acbcec2f09de5a/w2w/w2w.py#L521).

Yet since WRF is on an irregular grid, I should not do this.

@dargueso or @theendlessriver13 : I wonder if you have any ideas on how to do this?

So the procedure I use is:
1. I create a temporary .tif grid file from the WRF netcdf file, via [create_wrf_gridinfo](https://github.com/matthiasdemuzere/w2w/blob/18e484048211487e140e3a2f97acbcec2f09de5a/w2w/w2w.py#L512).
2. In sub-sequent steps, I use this .tif for all reprojections (see eg. [here](https://github.com/matthiasdemuzere/w2w/blob/18e484048211487e140e3a2f97acbcec2f09de5a/w2w/w2w.py#L621)), to reproject the higher resolution LCZ grid to the coarser resolution WRF grid.

But since the tmp .tif grid file definition is wrong, also the resulting reprojection is wrong.

So we need to come up with a better approach for the Reprojection. 
Yet I am not sure how this should best be done? Any ideas?

**Comment by pippo2013** [comment]
Thanks a lot @matthiasdemuzere for your investigation on this issue.  Unfortunately I do not have much experience on this topic. I am looking forward to your news!

**Comment by dargueso** [comment]
Hi @matthiasdemuzere, sorry for my late reply, I was travelling. The problem with lat/lon vs Lambert is always tricky. I would have to dig deeper to understand the whole process in order to give an opinion. I guess that the tif files must be regular lat/lon. Do you need to use a tif file for the reprojections in step 2? Because the alternative is to directly read the WRF grid and interpolate on to that grid and skip step 1, if that is possible. Does this sound like a feasible approach?

**Comment by matthiasdemuzere** [comment]
That is indeed what I have in mind as well. Mainly have to figure out how to get the right Transform tuple for the irregular wrf grid ...

If that is in place, it should work without the temporary .tif

**Comment by matthiasdemuzere** [comment]
That's indeed what I mean. Extract the proper projection parameters from the submitted geo_em wrf file. And then use these into the reproject directly  ...

**Comment by dargueso** [comment]
@matthiasdemuzere, the projection parameters in WRF files are a nightmare. I haven't managed to fully understand how they are interpreted by WRF to generate the domain and they don't always follow a standard, as far as I can tell. Plus there are a few projections that are commonly used. For example, Lambert, Mercator, Lat/lon and rotated pole. 
One option is to use wrf-python, which is able to read WRF files and extract the projection information into cartopy. I have often used it to make plots in WRF projection or transform the plots into a different projection, but not sure how to use it in other packages.

**Comment by NicMan89** [comment]
@matthiasdemuzere @dargueso  thanks a lot for sharing w2w tool!
I have tried to extract wrf grid projection following the [link](https://fabienmaussion.info/2018/01/06/wrf-projection/) posted from @pippo2013. The projection string is something like this: 
`'proj=lcc lat_0=41.7900199890137 lon_0=7.25 lat_1=30 lat_2=50 x_0=0 y_0=0 R=6370000 units=m no_defs'`
generate from: 
`wrf_proj = pyproj.Proj(proj='lcc', lat_1=wrf.TRUELAT1, lat_2=wrf.TRUELAT2,
                lat_0=wrf.MOAD_CEN_LAT, lon_0=wrf.STAND_LON, a=6370000, b=6370000)`

But I'm not sure this string is correct to generate the same grid in the geo_em file. 
After that I have tried to generate a .tif with LU_INDEX variable inside (following the same function name in the w2w.py script). I used for this rasterio package inside the attached file
[create_wrf_gridinfo.txt](https://github.com/matthiasdemuzere/w2w/files/8785369/create_wrf_gridinfo.txt).
Now the problem is that: the output .tif file is flipped horizontally and vertically. As @matthiasdemuzere says i think the mistake is in the transform tuple.
I hope this may help and I apologize in advance for any inaccuracies in the code.

**Comment by pippo2013** [comment]
Hi everyone! 
I tried to follow the approach you suggested,  using salem reprojection of WRF grid (from geo_em file) onto EU_LCZ map is fine:

ds2 = salem.open_xr_dataset('EU_LCZ_map_epsg4326.tif')
dse = salem.open_xr_dataset('geo_em.d03.nc')
lu_reproj = ds2.salem.transform(dse.LU_INDEX)

![Rome_epsg4326](https://user-images.githubusercontent.com/43202792/170678256-26ce8902-f7e2-4cf6-8248-939ca397fd8a.png)


However, I think it would be better to skip the geotiff since  WRF has an irregular grid.

**Comment by NicMan89** [comment]
Hi everyone. Following the @pippo2013 message, I have tried to use salem package to reproject native LCZ.tif in wrf grid from geo_em.
``` 
import salem
ds2 = salem.open_xr_dataset('EU_LCZ_map_epsg4326.tif')
dse = salem.open_xr_dataset('geo_em.d03.nc')

invlu_reproj = dse.salem.transform(ds2)
```
The result is:
``` 
In [50]: invlu_reproj
Out[50]: 
<xarray.Dataset>
Dimensions:      (west_east: 390, south_north: 399)
Coordinates:
  * west_east    (west_east) float64 2.36e+05 2.37e+05 ... 6.24e+05 6.25e+05
  * south_north  (south_north) float64 -1.66e+05 -1.65e+05 ... 2.31e+05 2.32e+05
Data variables:
    data         (south_north, west_east) int16 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0
Attributes:
    pyproj_srs:  +proj=lcc +lat_0=41.7900199890137 +lon_0=7.25 +lat_1=30 +lat...
```
with the shape and projection of wrf grid and land use from lcz.tif as in the plot
![invlu_reproj](https://user-images.githubusercontent.com/81507238/170690063-218fddf9-3f63-4230-ac38-e0aada7c28a8.png)

I don't know how the salem package resample the higher resolution LCZ grid to the coarser resolution WRF grid.
I hope this may help.

**Comment by matthiasdemuzere** [comment]
Hi @NicMan89 @pippo2013 

Thanks for looking into this.

I also reached out to Fabien, developer of Salem.
He said salem could indeed be used for this, or alternatively the [xesmf](https://xesmf.readthedocs.io/) package.

Unfortunately I don't manage to install xesmf via pip. So we could use salem.

Yet the `transform`is typically used to interpolate, with the output grid of similar of finer resolution than the input grid [here](https://salem.readthedocs.io/en/stable/gis.html#interpolation), with as default using the `nearest neighbour` value. So this is not what we need.

[Aggregation](https://salem.readthedocs.io/en/stable/gis.html#aggregation) is also possible, using [lookup_transform](https://salem.readthedocs.io/en/stable/gis.html#aggregation). Yet am not sure yet how  we can work with the `mode`, which we need to add the modal LCZ classes into the LU_INDEX table.

I'll keep looking what would be the best way to do this, ideally with the least additional packages.

**Comment by matthiasdemuzere** [comment]
@pippo2013 

I believe I managed to come up with a solution.
I tested this on your data, and the results look consistent now.
From left to right, LU_INDEX from geo_em.d03.nc, geo_em.d03_LCZ_extent.nc, and geo_em.d03_LCZ_params.nc

![image](https://user-images.githubusercontent.com/6926916/171665373-97e891ce-c9bb-47e0-90c5-482e626c4ab2.png)

It is still work in progress, as some of our tests still fail with this new implementation.
But it seems we are getting there.

If you want, you can try the branch out by installing:
`pip install git+https://github.com/matthiasdemuzere/w2w@fix_wrf_reproject`

**Comment by pippo2013** [comment]
Thank you so much @matthiasdemuzere!! I will test it immediately and let you know! :)

**Comment by matthiasdemuzere** [comment]
Hi @pippo2013 :

Thanks for testing this.

Questions / comments:

- could you provide some more details on the library issues you had? Something we should address?
- great that there is no longer a shift in the LCZ implementation
- the _41 will not show a shift anyhow, as we only change some global attributes in these files (eg. NUM_CAT_LAND).
