### ISSUE TITLE
Line 775 modification needed with python 3

### ISSUE THREAD

**Issue by AndresSimonMoral** [matthiasdemuzere/w2w#6]
I have changed 'frc_urb' by 'frc_urb.data' in line 775 to make w2w.py work. 
Maybe is it because I am using python 3?

Attached my geo_em and lcz files.

Cheers!
[vitoria-gasteiz_lcz_v1_big.tif.gz](https://github.com/matthiasdemuzere/w2w/files/7019605/vitoria-gasteiz_lcz_v1_big.tif.gz)
[geo_em.d03.nc.gz](https://github.com/matthiasdemuzere/w2w/files/7019607/geo_em.d03.nc.gz)

**Comment by matthiasdemuzere** [comment]
The tool has been build and tested with python 3.8. To create the exact same python environment, please follow the guidelines as provided in the README. 

As far as I can see, your LCZ map is produced by the LCZ Generator? Then please make sure to add the argument `-lcz_band 1` to your command:

`python w2w.py YOUR/INPUT/DIR vitoria-gasteiz_lcz_v1_big.tif geo_em.d03.nc -lcz_band 1`

This works for me, without changing the code.
I did get a warning in the end, but that is because files ` geo_em .. d01-d02 ... nc` are not available in the input directory.

**Comment by AndresSimonMoral** [comment]
Thanks for your reply, Matthias.

I am not using a virtual python environment. Instead, I downloaded the code and run it using pyhton3 command.
When trying your command I get python - python3 conversion-related problems.

Thanks again!

**Comment by matthiasdemuzere** [comment]
Then I would advise to use the provided virtual environment, to make sure the tool runs as expected. 

Perhaps I should also provide a requirement.txt file, so that users not familiar with conda can use this to properly set-up the w2w environment.

**Comment by AndresSimonMoral** [comment]
Thanks!

**Comment by matthiasdemuzere** [comment]
a `w2w_requirements.txt` file is added, and `README` is updated on how to create the proper environment using Python's venv tool.
