### ISSUE TITLE
revise efficiency wrf_remove_urban()

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/w2w#66]
This routine loops over all pixels (double loop over lat and lon), and replace every urban pixel with a corresponding natural pixel retrieved from its X neighbours.

The for-looping is rather time-consuming.
For small domains that is not an issue.

Yet for big domains it becomes one.
I am currently testing with a domain of 610 (lats) x590 (lons) pixels.

A full lat-cycle takes 23 seconds on my machine. 
Concluding all lat cycles thus takes 23*610 = 14030s = ~ 3.9 hours.

I think we should find a way to make this more efficient.
@dargueso and @theendlessriver13: would you guys have any ideas here?

In case you want to test it out yourself, you can find the input files [here](https://drive.google.com/drive/folders/1RzuYUC85XUyT2TgmmHWLfkQ860sr3X6Y?usp=sharing).

**Comment by dargueso** [comment]
@matthiasdemuzere, in the sample file you provided, there are grid points (ocean) that have LANDUSEF values of 1e20. How did you get these values? AFAIK, WRF generates geo_em files with LANDUSEF values between 0 and 1 for each category (level). The code expects that value to be between 0 and 1, also for ocean grid points, which will have 1 for level 16 (equivalent to category 17). As it is now, it will yield wrong data, because it understand 1e20 as valid value. I don't think this is correct because it must be defined for all grid points, including ocean ones. I have attached a screenshot.

Regardless of this issue, I'm working on speeding up the process.


![Screenshot 2022-06-30 at 18 02 31](https://user-images.githubusercontent.com/4198115/176724840-823bddd1-5b9b-4aee-ba5d-beb390b1bfd4.png)

**Comment by dargueso** [comment]
This is how geo_em.d02.nc file in sample_data looks like:
![Screenshot 2022-06-30 at 18 05 24](https://user-images.githubusercontent.com/4198115/176725287-71e58483-2ea1-4d39-a903-f8a5a1c008d1.png)

**Comment by dargueso** [comment]
I have made a first attempt to improved the efficiency of this bit of code. It now takes ~10% of the time it used to take. Depending on how big urban areas are and the number of nearest grid points asked for, this estimate may change.
As soon as we clarify the 1e20 values in your geo_em file, I will adapt the code accordingly and make a pull request.

**Comment by matthiasdemuzere** [comment]
Hi @dargueso, I got this file from coworkers. So I'll have to check with them ...
I'll get back to you!
