### ISSUE TITLE
Issue with metgrid reading geogrid files from w2w

### ISSUE THREAD

**Issue by phemiobe** [matthiasdemuzere/w2w#85]
Hello,

In my attempt to run metgrid with the outputs of w2w as my new geogrid files, metgrid failed with the following error.
Processing domain 1 of 4
ERROR: Couldn't open file ./[geo_em.d01.nc](http://geo_em.d01.nc/) for input.
Abort(56525808) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 56525808) - process 0.

I was able to run it, however, when I used the default geogrid files from MODIS. Note that in the conversion process I followed the guidelines as stated here while the files were renamed accordingly.

I have attached the geogrid files as well as the LCZ map for d04.

WRF version 4.3.1

Kindly assist,  Thanks as always.
[data_new.zip](https://github.com/matthiasdemuzere/w2w/files/9395139/data_new.zip)

**Comment by matthiasdemuzere** [comment]
Hi @phemiobe 

Your issue is probably related to issues #2, #9, #23 and #43: the fact that your WRF installation is not compiled with netcdf4/hdf5 enabled (the netcdf default for a long time now). So I would advise you to update your WRF install.

Alternatively you can install the unsupported `w2w` that produces netcdf3-formatted geo_em* files:

`pip install git+https://github.com/matthiasdemuzere/w2w.git@netcdf3_64bit`

**Comment by phemiobe** [comment]
solved when I recompile WRF. Thanks
